#!/usr/bin/env bash

command_exists() {
	command -v "$@" > /dev/null 2>&1
}


sh_c='sh -c'
if [ "$user" != 'root' ]; then
  if command_exists sudo; then
    sh_c='sudo -E sh -c'
  elif command_exists su; then
    sh_c='su -c'
  else
    echo "Error: this installer needs the ability to run commands as root."
    echo "We are unable to find either "sudo" or "su" available to make this happen."
    exit 1
  fi
fi


set -x
$sh_c 'apt-get update'
$sh_c "apt-get install -y -q isc-dhcp-server isc-dhcp-dev"
$sh_c 'dpkg -l isc-dhcp-server'

read -p "Enter Subnet (example: 10.10.0.0): " newsubnet
if [ -z "$newsubnet" ]
then
  newsubnet='10.10.0.0'
fi

read -p "Enter Netmask (example: 255.255.0.0): " newnetmask
if [ -z "$newnetmask" ]
then
  newnetmask='255.255.0.0'
fi

read -p "Enter Start Range (example: 10.10.0.20): " newrangestart
if [ -z "$newrangestart" ]
then
  newrangestart='10.10.0.20'
fi

read -p "Enter End Range (example: 10.10.254.254): " newrangeend
if [ -z "$newrangeend" ]
then
  newrangeend='10.10.254.254'
fi

read -p "Enter Routers (example: 10.10.0.254): " newrouters
if [ -z "$newrouters" ]
then
  newrouters='10.10.0.10'
fi


$sh_c "cat << EOF >> /etc/dhcp/dhcpd.conf
subnet $newsubnet netmask $newnetmask {
  range $newrangestart $newrangeend;
  option routers $newrouters;
}
EOF
"
ifconfig -a

read -p "Enter NIC to Serve (example: enp0s8: " newnic
if [ -z "$newnic" ]
then
  newnic='10.10.0.10'
fi
$sh_c sed -i "s/INTERFACE.*/INTERFACE=\"$newic\"/" /etc/default/isc-dhcp-server

echo "Restarting ISC-DHCP-SERVER Now..."
$sh_c "service isc-dhcp-server restart"

echo "All done!"

