#!/usr/bin/env bash

sshuttle -r $1 -l 0.0.0.0 -x $2 0/0


# On windows make sure to do the following:
# https://coderwall.com/p/adfxgw/sshuttle-on-windows
#route change 0.0.0.0 mask 0.0.0.0 192.168.1.1 metric 2
#route add 0.0.0.0 mask 0.0.0.0 192.168.1.200 metric 1
